---
sidebar: sidebar 
permalink: task-discover-storagegrid.html 
keywords: storagegrid, cluster, discover, manage, discovering, discover storagegrid 
summary: 發現本地環境中的StorageGRID系統，然後使用 Grid Manager 直接從NetApp Console管理它們。 
---
= 將StorageGRID系統新增至NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
使用 Grid Manager 直接從NetApp Console管理您的 StorageGrid 系統。

.所需的NetApp Console角色：
儲存管理員或系統健康專家。link:https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["了解NetApp Console存取角色"^]。

.開始之前
您需要以下內容：

* 使用版本 3.9.43 或更高版本的NetApp Console代理程式。您必須具有組織管理員角色才能安裝控制台代理程式。如果您不確定您的組織是否有控制台代理，或者是否需要建立一個，請聯絡您的NetApp Console管理員。 https://docs.netapp.com/us-en/console-setup-admin/task-user-settings.html#contact-your-organization-administrator["請聯絡您的組織管理員"^] 。
* 管理節點的網域名稱或IP位址。
* 管理節點的管理員憑證。
* 安裝在StorageGRID系統上的管理介面憑證。
+
https://docs.netapp.com/us-en/storagegrid-118/admin/configuring-custom-server-certificate-for-grid-manager-tenant-manager.html#add-a-custom-management-interface-certificate["了解有關在StorageGRID上安裝管理介面證書的更多信息"^]



.步驟
. 從導覽選單中，選擇*儲存>管理*。
. 選擇*系統*。
. 選擇*新增系統*並選擇*本機*。
. 在* StorageGRID*旁邊，選擇*發現*。
. 在控制台中的「StorageGRID 叢集詳細資料」頁面上，輸入管理節點的網域名稱或 IP 位址、節點的憑證，然後選擇「新增」。
. 控制台自動檢索StorageGRID管理介面憑證。在「批准證書」頁面上，查看證書詳細資訊。
. 若要使用不同的證書，請先在StorageGRID系統上設定。
+
.. 在您的本機StorageGRID系統中，請依照下列說明操作： https://docs.netapp.com/us-en/storagegrid-118/admin/configuring-custom-server-certificate-for-grid-manager-tenant-manager.html#add-a-custom-management-interface-certificate["在StorageGRID上安裝管理介面證書"^] 。
.. 在StorageGRID系統中設定憑證後，在控制台中的「核准憑證」頁面上選擇「*取消*」。
.. 在「StorageGRID 叢集詳細資料」頁面上，選擇「新增」。


. 或者，選擇「*複製憑證*」來複製憑證的詳細資料。如果需要，您可以使用證書詳細資訊執行額外的驗證。
. 執行下列操作之一：
+
.. 選擇*批准證書*以使用該證書。
+
NetApp Console顯示成功訊息，並透過驗證已核准的憑證來保護StorageGRID伺服器和控制台代理程式之間的所有通訊。

.. 選擇“*取消*”以結束發現程序而不驗證證書。
+
例如，如果您收到錯誤訊息，通知您需要更新StorageGRID管理證書，則可以選擇「*取消*」。

+
若要更新證書，請前往您的StorageGRID系統，更新證書，然後從NetApp Console重新啟動發現程序。




